all:
  hosts:
  children:
    client:
      hosts:
        100.124.157.113:
    server:
      hosts:
        100.66.102.123:
  vars:
    client:
      root_folder: "/opt/laps"
      data_folder: "/opt/laps/pictures/"
      service_folder: "/etc/systemd/system"
      logrotate:
        config_file: "/opt/laps/logrotate.cfg"
        cron:
          day: "*"
          hour: "*"
          minute: "*/10"
      gphoto:
        user: "pi"
        group: "pi"
        interval: 120 # seconds
        imagesize: 0 # see: gphoto2 --get-config imagesize
        log_file: "/opt/laps/gphoto.log"
      rclone:
        max_bandwith: "500K" # limit bandwith
        data_destination: "nextcloud:/TIMELAPS/test/"
        log_file: "/opt/laps/rclone.log"
        log_level: "INFO"
        cron:
          day: "*"
          hour: "*"
          minute: "*/10"
      metrics:
        stats_folder: "/opt/laps"
