all:
  hosts:
  children:
    client:
      hosts:
        100.124.157.113:
    server:
      hosts:
        100.66.102.123:
  vars:
    client:
      root_folder: "/opt/laps"
      data_folder: "/opt/laps/pictures/"
      logrotate:
        config_file: "/opt/laps/logrotate.cfg"
        state_file: "/opt/laps/logrotate.status"
        cron:
          day: "*"
          hour: "*"
          minute: "*/10"
      gphoto:
        user: "pi"
        group: "pi"
        cron:
          minute: "0,10,20,30,40,50"
          hour: "*"
          day: "*"
          month: "*"
        imagesize: 0 # see: gphoto2 --get-config imagesize
        log_file: "/opt/laps/gphoto.log"
      rclone:
        max_bandwith: "500K" # limit bandwith
        data_destination: "nextcloud:/TIMELAPS/ziegler/"
        log_file: "/opt/laps/rclone.log"
        log_level: "INFO"
        cron:
          day: "*"
          hour: "*"
          minute: "*"
      metrics:
        stats_folder: "/opt/laps"
